api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "cart-rules-validation"
type = "function"
uid = "c086c443-11d0-21b7-427a-5230c8448824e45b83a6"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.validations.generate.run"
  input_query = "src/cart_validations_generate_run.graphql"
  export = "cart-validations-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
